language: ruby
dist: focal
rvm: 2.5.8
node_js: 14

cache:
  bundler: true
  yarn: true
before_install:
  - yes | gem update --system --force
  - gem install bundler
install:
  - bundle install
  - yarn install
