---
version: "3.5"
services:
  hdm:
    image: example42/hdm:latest
    container_name: hdm
    environment:
      - PUID=1001
      - PGID=1001
      - USER_UID=1001
      - USER_GID=1001
      - TZ=Europe/Berlin
    # volumes:
    #   - /srv/data/hdm/db:/app/data/db
    ports:
      - 3000:3000
    restart: unless-stopped
